#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Michael K. Gunnulfsen

# Short bio or description (displayed in the header)
description: Dev. Oslo. 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xap1/v/t1.0-1/p200x200/10449491_10154365745465554_501816492351434760_n.jpg?oh=f4b07a5d4daa08435833336be0b9c3c1&oe=548135EE&__gda__=1416577809_e4dac91b07b93f37fc05d7c72638ea33

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: michaelkolleskov
  email: michaelgunnulfsen@gmail.com
  facebook: Michael.Kolleskov.Gunnulfsen
  flickr: 
  github: sslash
  instagram: michaelkolleskov
  linkedin: michaelgunnulfsen
  pinterest: 
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: michaelGunnulf
  stackoverflow: 

# Your disqus shortname, entering this will enable commenting on posts
disqus_shortname: sslash
disqus: sslash

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-55285705-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://sslash.github.io

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: pygments
permalink: /:title

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
